# 256 color enable
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

# prefix変更(Ctrl+S)
set -g prefix C-s
unbind C-b
bind-key s send-prefix

# new screen(Ctrl+c)
bind C-c new-window

# Ctlr+aで行頭移動
unbind C-a

# コピーモードをvi風に
set-window-option -g mode-keys vi

# detach ^D d
unbind d
bind C-d detach

# reload config
unbind r
bind C-r source-file "~/.config/tmux/tmux.conf" \; display-message "config reloaded"

# window 移動
unbind n
bind-key -r C-n next-window
unbind p
bind-key -r C-p previous-window

# split window
unbind %
unbind '"'
bind | split-window -h
bind / split-window -v

# vi like ペイン移動
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# ペインサイズ変更
bind-key -r C-l resize-pane -R 5
bind-key -r C-h resize-pane -L 5
bind-key -r C-j resize-pane -D 1
bind-key -r C-k resize-pane -U 1

# window色変更
set -g window-style 'fg=colour244,bg=colour234'
set -g window-active-style 'fg=white,bg=black'

# version
run-shell 'tmux setenv -g TMUX_VERSION $(tmux -V | \
                           sed -En "s/^tmux[^0-9]*([.0-9]+).*/\1/p")'

# utf8, 1.9以上では要らない
if-shell -b '[ "$(echo "$TMUX_VERSION < 1.9" | bc)" = 1 ]' \
  'set-window-option -g utf8 on'

# for claude code
set -s set-clipboard on
set -g allow-passthrough on
set -g mouse on
set -sg escape-time 0

##### 画面下ステータスライン設定 #####
set-window-option -g mode-keys vi
set-option -g status-right "#[fg=black,bold]#H"

# 文字コード設定(ver1.9以下)
if-shell -b '[ "$(echo "$TMUX_VERSION < 1.9" | bc)" = 1 ]' \
  'set-window-option -g utf8 on'

###
### COLOUR (Solarized light)
###
if-shell -b '[ "$(echo "$TMUX_VERSION < 2.9" | bc)" = 1 ]' " \
	set-option -g status-bg white; \
	set-option -g status-fg yellow; \
	set-option -g status-attr default;"
if-shell -b '[ "$(echo "$TMUX_VERSION < 2.9" | bc)" = 1 ]' " \
	set-window-option -g window-status-fg brightyellow; \
	set-window-option -g window-status-bg default;"
if-shell -b '[ "$(echo "$TMUX_VERSION < 2.9" | bc)" = 1 ]' " \
	set-window-option -g window-status-current-fg brightred; \
	set-window-option -g window-status-current-bg default;"
if-shell -b '[ "$(echo "$TMUX_VERSION < 2.9" | bc)" = 1 ]' " \
	set-option -g pane-border-fg white; \
	set-option -g pane-active-border-fg brightcyan;"
if-shell -b '[ "$(echo "$TMUX_VERSION < 2.9" | bc)" = 1 ]' " \
	set-option -g message-bg white; \
	set-option -g message-fg brightred;"

if-shell -b '[ "$(echo "$TMUX_VERSION >= 2.9" | bc)" = 1 ]' " \
  set-option -g status-style bg=white,fg=yellow; \
  set-window-option -g window-status-style fg=brightyellow; \
  set-window-option -g window-status-current-style fg=brightred; \
  set-option -g pane-border-style fg=white ; \
  set-option -g pane-active-border-style fg=brightcyan; \
  set-option -g message-style fg=brightred,bg=white;"

# pane number display
set-option -g display-panes-active-colour blue
set-option -g display-panes-colour brightred

# clock
set-window-option -g clock-mode-colour green
